region         = "ap-south-1"
cluster_name   = "simple-time-cluster"
vpc_name       = "simple-time-vpc"
vpc_cidr       = "10.0.0.0/16"
public_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets = ["10.0.3.0/24", "10.0.4.0/24"]
desired_capacity = 1
max_size         = 2
min_size         = 1
instance_type    = "t3.medium"
docker_image     = "sparshagrawal/simpletimeservice:latest"
helm_chart_name  = "simple-time-service"
helm_namespace   = "default"