apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: simple-time-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7000